FROM athes/swflib:debian-slim as build-stage

ARG SWFLIB_STATIC=ON
ARG CMAKE_BUILD_TYPE=Release

WORKDIR /src/detfm
COPY . .

WORKDIR /build/detfm
RUN cmake /src/detfm -DSWFLIB_STATIC=$SWFLIB_STATIC && \
    cmake --build . && \
    cmake --install . --strip

FROM athes/unpacker:debian-slim

WORKDIR /app
COPY --from=build-stage /usr/local/lib/swflib.so /usr/local/lib/
COPY --from=build-stage /usr/local/bin/detfm /usr/local/bin/
COPY classdef ./classdef
